### ISSUE TITLE
Wont Attach

### ISSUE THREAD

**Issue by NuclearxAtomic** [TheUnknownCod3r/BO4-Lucy-MP-Base#1]
Looks like after the  new update it wont attach or a few of the important ptr have changed

**Comment by TheUnknownCod3r** [comment]
I'll take a look, but it was probably an injector issue, not the menu base. The codebase itself is update independent.

**Comment by TheUnknownCod3r** [comment]
Injects fine, was probably a compiler issue that was fixed independently. For future note regarding issues like these, the GSC code is update independent, however the Compiler used to inject can be broken at any time. The menu base *should* never need updated when a new version drops, however the compiler may need an update.
